name: Node

'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out most recent version of code
      uses: actions/checkout@v1
      
    - name: Using Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    - name: Clean npm install
      run: npm ci

    - name: Run Database Backend
      run: npm run run_db

    - name: test
      run: docker ps

    - name: Set-up Database
      run: npm run setup_db
      
    - name: Unit tests
      run: npm test

    - name: Code Coverage
      run: npm run test_coverage